/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module user_project_wrapper(wb_clk_i, wb_rst_i, wbs_stb_i, wbs_cyc_i, wbs_we_i, wbs_sel_i, wbs_dat_i, wbs_adr_i, wbs_ack_o, wbs_dat_o, la_data_in, la_data_out, la_oenb, io_in, io_out, io_oeb, analog_io, user_clock2, user_irq);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  inout [28:0] analog_io;
  wire [28:0] analog_io;
  input [37:0] io_in;
  wire [37:0] io_in;
  output [37:0] io_oeb;
  wire [37:0] io_oeb;
  output [37:0] io_out;
  wire [37:0] io_out;
  wire \irq_internal[0] ;
  wire \irq_internal[1] ;
  wire \irq_internal[2] ;
  wire \irq_internal[3] ;
  input [127:0] la_data_in;
  wire [127:0] la_data_in;
  output [127:0] la_data_out;
  wire [127:0] la_data_out;
  input [127:0] la_oenb;
  wire [127:0] la_oenb;
  input user_clock2;
  wire user_clock2;
  output [2:0] user_irq;
  wire [2:0] user_irq;
  input wb_clk_i;
  wire wb_clk_i;
  input wb_rst_i;
  wire wb_rst_i;
  output wbs_ack_o;
  wire wbs_ack_o;
  input [31:0] wbs_adr_i;
  wire [31:0] wbs_adr_i;
  input wbs_cyc_i;
  wire wbs_cyc_i;
  input [31:0] wbs_dat_i;
  wire [31:0] wbs_dat_i;
  output [31:0] wbs_dat_o;
  wire [31:0] wbs_dat_o;
  input [3:0] wbs_sel_i;
  wire [3:0] wbs_sel_i;
  input wbs_stb_i;
  wire wbs_stb_i;
  input wbs_we_i;
  wire wbs_we_i;
  peripheral_subsystem_wb_wrapper mprj (
    .gpio_in(io_in[19:18]),
    .gpio_oe(2'b11),
    .gpio_out(io_out[19:18]),
    .i2c_scl_i(io_in[16]),
    .i2c_scl_o(io_out[16]),
    .i2c_scl_oen_o(1'b1),
    .i2c_sda_i(io_in[17]),
    .i2c_sda_o(io_out[17]),
    .i2c_sda_oen_o(1'b1),
    .irq({ \irq_internal[3] , user_irq }),
    .spi0_csb(io_out[10]),
    .spi0_miso(io_in[8]),
    .spi0_mosi(io_out[9]),
    .spi0_sclk(io_out[11]),
    .spi1_csb(io_out[14]),
    .spi1_miso(io_in[12]),
    .spi1_mosi(io_out[13]),
    .spi1_sclk(io_out[15]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wbs_ack_o(wbs_ack_o),
    .wbs_adr_i(wbs_adr_i),
    .wbs_cyc_i(wbs_cyc_i),
    .wbs_dat_i(wbs_dat_i),
    .wbs_dat_o(wbs_dat_o),
    .wbs_sel_i(wbs_sel_i),
    .wbs_stb_i(wbs_stb_i),
    .wbs_we_i(wbs_we_i)
  );
  assign _27_ = 1'b1;
  assign _26_ = 1'b1;
  assign _25_ = 1'b1;
  assign _24_ = 1'b1;
  assign _23_ = 1'b1;
  assign _21_ = 1'b1;
  assign _20_ = 1'b1;
  assign _19_ = 1'b1;
  assign _18_ = 1'b1;
  assign _17_ = 1'b1;
  assign _16_ = 1'b1;
  assign _15_ = 1'b1;
  assign _14_ = 1'b1;
  assign _13_ = 1'b1;
  assign _12_ = 1'b1;
  assign _10_ = 1'b1;
  assign _09_ = 1'b1;
  assign _08_ = 1'b1;
  assign _07_ = 1'b1;
  assign _06_ = 1'b0;
  assign _05_ = 1'b0;
  assign _04_ = 1'b0;
  assign _03_ = 1'b1;
  assign _02_ = 1'b0;
  assign _01_ = 1'b0;
  assign _37_ = 1'b0;
  assign _36_ = 1'b1;
  assign _35_ = 1'b1;
  assign _34_ = 1'b1;
  assign _33_ = 1'b1;
  assign _32_ = 1'b1;
  assign _31_ = 1'b1;
  assign _22_ = 1'b1;
  assign _11_ = 1'b1;
  assign _00_ = 1'b1;
  assign _40_ = user_irq[2];
  assign _39_ = user_irq[1];
  assign _38_ = user_irq[0];
  assign \irq_internal[2]  = user_irq[2];
  assign \irq_internal[1]  = user_irq[1];
  assign \irq_internal[0]  = user_irq[0];
  assign _30_ = 1'b1;
  assign _29_ = 1'b1;
  assign _28_ = 1'b1;
  assign io_oeb = 38'b11111111111111111111110001000111111111;
endmodule
